Homework done
Azadios/hh-SQL-homework pull request #1
Opened 2020-12-07 15:44 UTC by Azadios

Мне показалось странным, что area_id принадлежит employer, а не vacancy, но решил, что должно быть как в презентации.
И да, в тексте домашнего задания в 4 пункте просилось среднюю среднюю выплату, а в скобках указана формула для среднего интервала выплат. Сделал для средней выплаты, могу переделать.

2020-12-07 15:50 UTC, Azadios commented on getData.sql
> +        END AS compensation_from
Можно ли было используя уже gross значения прямо здесь создать 3 колонку с average_compensation?
Как я понял, можно либо ещё раз написать эти условия при создании 3 колонки, либо создать ещё одну временную таблицу и ещё раз пройтись по уже gross значениям, но нельзя использовать преобразованные данные этого же SELECT'а.

2020-12-07 15:55 UTC, Azadios commented on getData.sql
> +)
Можно ли было используя уже gross значения прямо здесь создать 3 колонку с average_compensation?
Как я понял, можно либо ещё раз написать эти условия при создании 3 колонки, либо создать ещё одну временную таблицу и ещё раз пройтись по уже gross значениям, но нельзя использовать преобразованные данные этого же SELECT'а.

2020-12-07 18:03 UTC, eldmitrieva requested changes

2020-12-07 18:03 UTC, eldmitrieva commented on getData.sql
> +)
Да, можно было бы создать третью колонку. Можно было бы и перевод добавить внутрь avg(), но было бы очень неаккуратно

2020-12-07 18:03 UTC, eldmitrieva commented on getData.sql
> +FROM response_per_vacancy_ordered
Тут не хватает сортировки, сортировка в response_per_vacancy_ordered тут уже не работает

2020-12-07 18:03 UTC, eldmitrieva commented on getData.sql
> +    INNER JOIN employer ON vacancy.employer_id = employer.employer_id
работодатели, у которых нет либо вакансий, либо откликов, не попадут в топ, надо поправить

2020-12-07 18:03 UTC, eldmitrieva commented on getData.sql
> +        COUNT(*) OVER (PARTITION BY vacancy.vacancy_id) AS response_count
ты тут считаешь количество откликов для каждой вакансии, у тебя так какие-то работодатели будут в выборке несколько раз, такого быть не должно

2020-12-07 18:03 UTC, eldmitrieva commented on getData.sql
> +    MIN(response.created_at - vacancy.created_at) OVER (PARTITION BY area_id) AS "Минимальное время отклика",
Неправильно. Если в скрипте заполнения данных поставишь разные created_at, увидишь ошибку

2020-12-08 16:34 UTC, eldmitrieva requested changes

2020-12-08 16:34 UTC, eldmitrieva commented on getData.sql
> +        employer_name,
У тебя employer_name при создании не указано как уникальное, поэтому чисто теоретически у тебя могут быть несколько работодателей с одинаковым названием, но разными id, здесь они будут считаться одним работодателем.  А если дублей не будет, то и DISTINCT не нужен

2020-12-08 16:51 UTC, Azadios commented on getData.sql
> +        employer_name,
Добавил проверку на id.
Хотя, наверное, стоило потребовать уникальность имён, но в заданиях нигде явно не говорилось о таком, решил не менять поведение всей таблицы.

2020-12-09 09:20 UTC, eldmitrieva commented on getData.sql
> +        employer_name,
Уникальность имен не нужна, иногда бывает, что есть компании с одинаковым названием, особенно если это какой-нибудь маленький магазин у дома.

2020-12-09 09:31 UTC, eldmitrieva requested changes

2020-12-09 09:31 UTC, eldmitrieva commented on getData.sql
> +    GROUP BY employer_name
здесь тогда тоже должен быть employer_id, иначе ты компании с одним названием считаешь как одну, а может быть и так, что две компании с одинаковым названием набрали близкое максимальное количество откликов, тогда они обе должны быть в результирующей выборке, но будет только одна

2020-12-09 09:31 UTC, eldmitrieva commented on getData.sql
> +SELECT DISTINCT
зачем distinct, если ты сгруппировал по area_id?

2020-12-09 12:05 UTC, Azadios commented on getData.sql
> +SELECT DISTINCT
Забыл убрать

2020-12-09 12:18 UTC, Azadios commented on getData.sql
> +    GROUP BY employer_name
Верно

2020-12-09 14:47 UTC, eldmitrieva approved these changes

2021-05-09 02:21 UTC, closed without merging